"""Curated host-facing contract for Pynchy plugins."""

from __future__ import annotations

from pynchy.plugins.agent_hooks import (
    agent_hook_mounts,
    collect_agent_hook_specs,
    container_agent_hook_configs,
    host_agent_hook_configs,
)
from pynchy.plugins.capabilities import (
    ActionIntentContract,
    ActionIntentDraft,
    ActionIntentReceipt,
    ApprovalContract,
    ApprovalMode,
    ApprovalTrigger,
    AuditContract,
    CapabilityCatalogError,
    CapabilityDescriptor,
    CapabilityId,
    CapabilityKind,
    CapabilityProbeContext,
    CapabilityProbeResult,
    CapabilityRequirement,
    CapabilityRequirementKind,
    CapabilityStatus,
    HostActionAccess,
    HostActionDescriptor,
    HostActionHandler,
    HostActionRegistration,
    HostToolName,
    IdempotencyContract,
    IdempotencyMode,
    ProbeStatus,
    ResolvedCapability,
    WorkspaceCapabilitySnapshot,
    missing_workspace_tool,
    validate_host_action_descriptors,
)
from pynchy.plugins.channel_runtime import (
    ChannelPluginContext,
    load_channels,
    resolve_default_channel,
)
from pynchy.plugins.computer_use import (
    ComputerUseAction,
    ComputerUseBackend,
    ComputerUseBackendAvailability,
    ComputerUseRequest,
    ComputerUseRouterConfig,
    SourceGroup,
)
from pynchy.plugins.connections import (
    ConnectionRuntime,
    ConnectionRuntimeContext,
    load_connection_runtimes,
)
from pynchy.plugins.contracts import (
    SUPPORTED_AUDIO_SUFFIXES,
    AgentCoreSpec,
    AgentHookSpec,
    AudioMetadataPatch,
    AudioTranscriptionResult,
    Channel,
    ChannelFormatter,
    InboundAudioAttachment,
    InboundAudioProcessingRequest,
    InboundAudioProcessingResult,
    InboundFetchResult,
    JobSpec,
    McpServerSpec,
    NewMessage,
    OutboundEvent,
    OutboundEventType,
    PluginVerification,
    RuntimeProvider,
    WorkspaceSpec,
    is_supported_audio_filename,
)
from pynchy.plugins.hookspecs import PynchySpec
from pynchy.plugins.host_actions import (
    HostActionCatalog,
    clear_host_action_catalog_cache,
    get_host_action_catalog,
    initialize_host_action_catalog,
)
from pynchy.plugins.mcp_server import McpServerConfig
from pynchy.plugins.observers import ObserverProvider, attach_observers
from pynchy.plugins.registry import collect_hook_results, get_plugin_manager
from pynchy.plugins.session_lifecycle import prepare_context_reset
from pynchy.plugins.webhooks import (
    WebhookActor,
    WebhookAuthenticationError,
    WebhookConfigurationError,
    WebhookConversation,
    WebhookDiscard,
    WebhookEvent,
    WebhookLifecycle,
    WebhookLifecycleDelivery,
    WebhookPayloadError,
    WebhookProcessingError,
    WebhookRoute,
    collect_webhook_routes,
    validate_webhook_routes,
)

__all__ = [
    "SUPPORTED_AUDIO_SUFFIXES",
    "ActionIntentContract",
    "ActionIntentDraft",
    "ActionIntentReceipt",
    "AgentCoreSpec",
    "AgentHookSpec",
    "ApprovalContract",
    "ApprovalMode",
    "ApprovalTrigger",
    "AudioMetadataPatch",
    "AudioTranscriptionResult",
    "AuditContract",
    "CapabilityCatalogError",
    "CapabilityDescriptor",
    "CapabilityId",
    "CapabilityKind",
    "CapabilityProbeContext",
    "CapabilityProbeResult",
    "CapabilityRequirement",
    "CapabilityRequirementKind",
    "CapabilityStatus",
    "Channel",
    "ChannelFormatter",
    "ChannelPluginContext",
    "ComputerUseAction",
    "ComputerUseBackend",
    "ComputerUseBackendAvailability",
    "ComputerUseRequest",
    "ComputerUseRouterConfig",
    "ConnectionRuntime",
    "ConnectionRuntimeContext",
    "HostActionAccess",
    "HostActionCatalog",
    "HostActionDescriptor",
    "HostActionHandler",
    "HostActionRegistration",
    "HostToolName",
    "IdempotencyContract",
    "IdempotencyMode",
    "InboundAudioAttachment",
    "InboundAudioProcessingRequest",
    "InboundAudioProcessingResult",
    "InboundFetchResult",
    "JobSpec",
    "McpServerConfig",
    "McpServerSpec",
    "NewMessage",
    "ObserverProvider",
    "OutboundEvent",
    "OutboundEventType",
    "PluginVerification",
    "ProbeStatus",
    "PynchySpec",
    "ResolvedCapability",
    "RuntimeProvider",
    "SourceGroup",
    "WebhookActor",
    "WebhookAuthenticationError",
    "WebhookConfigurationError",
    "WebhookConversation",
    "WebhookDiscard",
    "WebhookEvent",
    "WebhookLifecycle",
    "WebhookLifecycleDelivery",
    "WebhookPayloadError",
    "WebhookProcessingError",
    "WebhookRoute",
    "WorkspaceCapabilitySnapshot",
    "WorkspaceSpec",
    "agent_hook_mounts",
    "attach_observers",
    "clear_host_action_catalog_cache",
    "collect_agent_hook_specs",
    "collect_hook_results",
    "collect_webhook_routes",
    "container_agent_hook_configs",
    "get_host_action_catalog",
    "get_plugin_manager",
    "host_agent_hook_configs",
    "initialize_host_action_catalog",
    "is_supported_audio_filename",
    "load_channels",
    "load_connection_runtimes",
    "missing_workspace_tool",
    "prepare_context_reset",
    "resolve_default_channel",
    "validate_host_action_descriptors",
    "validate_webhook_routes",
]
