"""Built-in semantic action declarations, grouped independently from their contract."""

from __future__ import annotations

from typing import TYPE_CHECKING

from pynchy.actions._spec_helpers import agent_action, mcp_action
from pynchy.actions._specs_computer_use import COMPUTER_USE_ACTION_SPECS
from pynchy.actions._specs_core import CORE_ACTION_SPECS
from pynchy.actions._specs_gog import GOG_ACTION_SPECS

if TYPE_CHECKING:
    from pynchy.actions._contract import ActionSpec

# NOTE: Update docs/architecture/action-coverage.md when changing action
# evidence requirements or the canary contract.
ACTION_SPECS: tuple[ActionSpec, ...] = (
    *CORE_ACTION_SPECS,
    agent_action(
        "desktop.screenshot.capture",
        "desktop-screenshot",
        "Capture a host desktop screenshot for a workspace.",
        "take_screenshot",
        canary="desktop.screenshot.round.trip",
    ),
    agent_action(
        "desktop.screenshot.analyze",
        "desktop-screenshot",
        "Analyze a workspace desktop screenshot with a vision model.",
        "analyze_screenshot",
        canary="desktop.screenshot.round.trip",
    ),
    *COMPUTER_USE_ACTION_SPECS,
    *GOG_ACTION_SPECS,
    agent_action(
        "integration.google.profile.setup",
        "google-setup",
        "Set up Google services for an authorized browser profile.",
        "setup_google_{profile}",
        canary="google.profile.setup",
    ),
    agent_action(
        "integration.slack.session.setup",
        "slack-token-extractor",
        "Create a persistent Slack browser session through interactive login.",
        "setup_slack_session",
        canary="slack.session.setup",
    ),
    agent_action(
        "integration.slack.tokens.refresh",
        "slack-token-extractor",
        "Refresh Slack browser tokens from a persistent authenticated session.",
        "refresh_slack_tokens",
        canary="slack.tokens.refresh",
    ),
    agent_action(
        "social.x.session.setup",
        "x-integration",
        "Create a persistent X browser session through interactive login.",
        "setup_x_session",
        canary="social.x.session.setup",
    ),
    agent_action(
        "social.x.post",
        "x-integration",
        "Publish a post to X.",
        "x_post",
        canary="social.x.round.trip",
    ),
    agent_action(
        "social.x.like",
        "x-integration",
        "Like a post on X.",
        "x_like",
        canary="social.x.round.trip",
    ),
    agent_action(
        "social.x.reply",
        "x-integration",
        "Reply to a post on X.",
        "x_reply",
        canary="social.x.round.trip",
    ),
    agent_action(
        "social.x.repost",
        "x-integration",
        "Repost a post on X.",
        "x_retweet",
        canary="social.x.round.trip",
    ),
    agent_action(
        "social.x.quote",
        "x-integration",
        "Quote a post on X.",
        "x_quote",
        canary="social.x.round.trip",
    ),
    mcp_action(
        "linear.team.list",
        "linear",
        "List teams available through the configured Linear workspace.",
        "linear_list_teams",
        canary="linear.workspace.round.trip",
    ),
    mcp_action(
        "linear.issue.list",
        "linear",
        "List issues from the configured Linear workspace.",
        "linear_list_issues",
        canary="linear.workspace.round.trip",
    ),
    mcp_action(
        "linear.issue.search",
        "linear",
        "Find issues by title text through the configured Linear workspace.",
        "linear_search_issues",
        canary="linear.workspace.round.trip",
    ),
    mcp_action(
        "linear.issue.read",
        "linear",
        "Read one issue from the configured Linear workspace.",
        "linear_get_issue",
        canary="linear.workspace.round.trip",
    ),
    mcp_action(
        "linear.issue.archive",
        "linear",
        "Archive an authorized Linear issue without trashing it.",
        "linear_archive_issue",
    ),
    mcp_action(
        "linear.issue.create",
        "linear",
        "Create an issue in a selected Linear team.",
        "linear_create_issue",
        canary="linear.workspace.round.trip",
    ),
    mcp_action(
        "linear.todo.list",
        "linear",
        "List Linear todo issues for a Pynchy workspace.",
        "linear_list_todos",
        canary="linear.workspace.round.trip",
    ),
    mcp_action(
        "linear.todo.create",
        "linear",
        "Propose a Linear work item for a Pynchy workspace.",
        "linear_create_todo",
        canary="linear.workspace.round.trip",
    ),
    agent_action(
        "linear.comment.create",
        "linear",
        "Add a Linear comment through the host-owned write boundary.",
        "linear_create_comment",
        canary="linear.workspace.round.trip",
    ),
    mcp_action(
        "linear.attachment.create",
        "linear",
        "Attach an external resource to a Linear issue.",
        "linear_create_attachment",
        canary="linear.workspace.round.trip",
    ),
    mcp_action(
        "linear.attachment.resolve",
        "linear",
        "Resolve an external resource URL to attached Linear issues.",
        "linear_find_issues_by_attachment_url",
        canary="linear.workspace.round.trip",
    ),
    agent_action(
        "linear.todo.plan",
        "linear",
        "Persist a concrete Linear plan and request human plan approval.",
        "linear_submit_plan",
        canary="linear.workspace.round.trip",
    ),
    agent_action(
        "linear.todo.move",
        "linear",
        "Move a workspace Linear item within the caller's current authority.",
        "linear_move_todo",
        canary="linear.workspace.round.trip",
    ),
    agent_action(
        "linear.workitem.list",
        "linear",
        "List durable Pynchy executions linked to Linear work items.",
        "linear_list_work_items",
    ),
    agent_action(
        "linear.workitem.reconcile",
        "linear",
        "Reconcile an uncertain or reviewed conflicted Linear work-item transition "
        "from provider state.",
        "linear_reconcile_work_item",
    ),
    mcp_action(
        "mail.proton.mailbox.list",
        "proton-mail",
        "List mailboxes available through Proton Bridge.",
        "proton_list_mailboxes",
        canary="proton.mail.round.trip",
    ),
    mcp_action(
        "mail.proton.message.list",
        "proton-mail",
        "List messages from a Proton Mail mailbox.",
        "proton_list_mail",
        canary="proton.mail.round.trip",
    ),
    mcp_action(
        "mail.proton.message.read",
        "proton-mail",
        "Read a Proton Mail message without changing its read state.",
        "proton_read_mail",
        canary="proton.mail.round.trip",
    ),
    mcp_action(
        "mail.proton.message.send",
        "proton-mail",
        "Send a plain-text email through Proton Bridge SMTP.",
        "proton_send_mail",
        canary="proton.mail.round.trip",
    ),
    mcp_action(
        "mail.proton.message.delete",
        "proton-mail",
        "Permanently delete a Proton Mail message by Message-ID.",
        "proton_delete_mail",
        canary="proton.mail.round.trip",
    ),
    agent_action(
        "marketplace.health.read",
        "marketplace-health",
        "Read aggregate marketplace decision counts and reader health.",
        "marketplace_health_snapshot",
    ),
    agent_action(
        "secret.vaultwarden.read",
        "vaultwarden",
        "Read one exact-name item from channel-granted Vaultwarden collections.",
        "get_secret",
    ),
    agent_action(
        "secret.vaultwarden.admin",
        "vaultwarden-admin",
        "Administer Vaultwarden without secret-valued tool arguments.",
        "manage_vaultwarden",
    ),
    agent_action(
        "chat.matrix.route.read",
        "matrix-gateway",
        "Read messages from this conversation's configured Matrix route.",
        "matrix_route_read",
    ),
    agent_action(
        "chat.matrix.route.send",
        "matrix-gateway",
        "Send an exactly approved reply on this conversation's Matrix route.",
        "matrix_route_send",
    ),
    mcp_action(
        "calendar.google.calendar.list",
        "gcal",
        "List calendars through the configured Google Calendar MCP server.",
        "list-calendars",
        canary="calendar.google.round.trip",
    ),
    mcp_action(
        "calendar.google.event.list",
        "gcal",
        "List Google Calendar events in a selected calendar.",
        "list-events",
        canary="calendar.google.round.trip",
    ),
    mcp_action(
        "calendar.google.event.create",
        "gcal",
        "Create a Google Calendar event.",
        "create-event",
        canary="calendar.google.round.trip",
    ),
    mcp_action(
        "calendar.google.event.read",
        "gcal",
        "Read a Google Calendar event by ID.",
        "get-event",
        canary="calendar.google.round.trip",
    ),
    mcp_action(
        "calendar.google.event.delete",
        "gcal",
        "Delete a Google Calendar event.",
        "delete-event",
        canary="calendar.google.round.trip",
    ),
    mcp_action(
        "drive.google.file.search",
        "gdrive",
        "Search Google Drive through the configured read-only MCP server.",
        "gdrive_search",
        canary="drive.google.round.trip",
    ),
    mcp_action(
        "drive.google.file.read",
        "gdrive",
        "Read a configured Google Drive fixture through the MCP server.",
        "gdrive_read_file",
        canary="drive.google.round.trip",
    ),
    mcp_action(
        "notebook.kernel.start",
        "notebook-server",
        "Start an isolated notebook kernel.",
        "start_kernel",
    ),
    mcp_action(
        "notebook.cell.execute",
        "notebook-server",
        "Execute code in an active notebook kernel.",
        "execute_cell",
    ),
    mcp_action(
        "notebook.markdown.add",
        "notebook-server",
        "Add markdown to an active notebook.",
        "add_markdown",
    ),
    mcp_action(
        "notebook.file.save",
        "notebook-server",
        "Save an active notebook under a new name.",
        "save_as",
    ),
    mcp_action("notebook.file.read", "notebook-server", "Read a saved notebook.", "read_notebook"),
    mcp_action("notebook.file.list", "notebook-server", "List saved notebooks.", "list_notebooks"),
    mcp_action(
        "notebook.kernel.list", "notebook-server", "List active notebook kernels.", "list_kernels"
    ),
    mcp_action(
        "notebook.kernel.stop",
        "notebook-server",
        "Shut down an active notebook kernel.",
        "shutdown_kernel",
    ),
)
