"""Startup recovery behavior for repository worktrees and hooks."""

from __future__ import annotations

import subprocess  # noqa: S404 - tests exercise fixed git-result failure paths.
from dataclasses import dataclass
from typing import TYPE_CHECKING
from unittest.mock import patch

import pytest

from pynchy.host.git_ops.api import (
    RepoContext,
    WorktreeError,
    install_repo_hooks,
    reconcile_worktrees_at_startup,
)

if TYPE_CHECKING:
    from pathlib import Path


@dataclass(frozen=True)
class _StartupRuntime:
    home_dir: Path
    project_root: Path
    configured_tokens: dict[str, str | None]


def _repo_context(tmp_path: Path) -> tuple[RepoContext, _StartupRuntime]:
    project_root = tmp_path / "project"
    worktrees_dir = project_root / "worktrees"
    project_root.mkdir()
    return (
        RepoContext(slug="owner/repo", root=project_root, worktrees_dir=worktrees_dir),
        _StartupRuntime(
            home_dir=tmp_path / "home",
            project_root=project_root,
            configured_tokens={},
        ),
    )


def _reconcile(
    repo_context: RepoContext,
    runtime: _StartupRuntime,
    *,
    folders: list[str] | None = None,
    git_runner: object | None = None,
) -> None:
    git_patch = (
        patch("pynchy.host.git_ops.worktree.run_git", side_effect=git_runner)
        if git_runner is not None
        else patch(
            "pynchy.host.git_ops.worktree.run_git",
            return_value=subprocess.CompletedProcess([], 0),
        )
    )
    with (
        patch("pynchy.host.git_ops.worktree._runtime.runtime", runtime),
        patch(
            "pynchy.host.git_ops.worktree.repo_manager.get_repo_context",
            return_value=repo_context,
        ),
        patch(
            "pynchy.host.git_ops.worktree.repo_manager.ensure_repo_cloned",
            return_value=True,
        ),
        patch("pynchy.host.git_ops.worktree.repo_manager.get_repo_token", return_value=None),
        patch("pynchy.host.git_ops.worktree.install_repo_hooks"),
        git_patch,
    ):
        reconcile_worktrees_at_startup({"owner/repo": folders or []})


@pytest.mark.parametrize(
    "failure",
    [
        subprocess.CompletedProcess([], 1, "", "installer failed"),
        OSError("installer unavailable"),
    ],
)
def test_hook_installation_failure_isolated_from_startup(
    tmp_path: Path,
    failure: object,
) -> None:
    (tmp_path / "prek.toml").write_text("repos = []")
    installer_patch = (
        patch(
            "pynchy.host.git_ops.worktree._run_hook_installer",
            return_value=failure,
        )
        if isinstance(failure, subprocess.CompletedProcess)
        else patch(
            "pynchy.host.git_ops.worktree._run_hook_installer",
            side_effect=failure,
        )
    )
    with installer_patch:
        install_repo_hooks(tmp_path)


def test_obsolete_hook_retirement_failure_isolated_from_startup(tmp_path: Path) -> None:
    (tmp_path / "prek.toml").write_text("repos = []")
    hooks = tmp_path / ".git" / "hooks"
    hooks.mkdir(parents=True)
    (hooks / "pre-commit").write_text("File generated by prek:")
    (hooks / "pre-commit.legacy").write_text(
        "File generated by pre-commit: --config=.pre-commit-config.yaml"
    )
    success = subprocess.CompletedProcess([], 0)
    failure = subprocess.CompletedProcess([], 1, "", "overwrite failed")
    with patch(
        "pynchy.host.git_ops.worktree._run_hook_installer",
        side_effect=[success, failure],
    ) as installer:
        install_repo_hooks(tmp_path)
    assert installer.call_count == 2


def test_startup_skips_unavailable_repo_without_creating_worktrees(tmp_path: Path) -> None:
    repo_context, runtime = _repo_context(tmp_path)
    with (
        patch("pynchy.host.git_ops.worktree._runtime.runtime", runtime),
        patch(
            "pynchy.host.git_ops.worktree.repo_manager.get_repo_context",
            return_value=repo_context,
        ),
        patch(
            "pynchy.host.git_ops.worktree.repo_manager.ensure_repo_cloned",
            return_value=False,
        ),
        patch("pynchy.host.git_ops.worktree.ensure_worktree") as ensure,
    ):
        reconcile_worktrees_at_startup({"owner/repo": ["group"]})
    ensure.assert_not_called()


def test_startup_continues_when_one_worktree_cannot_be_created(tmp_path: Path) -> None:
    repo_context, runtime = _repo_context(tmp_path)
    with (
        patch("pynchy.host.git_ops.worktree._runtime.runtime", runtime),
        patch(
            "pynchy.host.git_ops.worktree.repo_manager.get_repo_context",
            return_value=repo_context,
        ),
        patch(
            "pynchy.host.git_ops.worktree.repo_manager.ensure_repo_cloned",
            return_value=True,
        ),
        patch("pynchy.host.git_ops.worktree.repo_manager.get_repo_token", return_value=None),
        patch("pynchy.host.git_ops.worktree.install_repo_hooks"),
        patch(
            "pynchy.host.git_ops.worktree.run_git", return_value=subprocess.CompletedProcess([], 0)
        ),
        patch(
            "pynchy.host.git_ops.worktree.ensure_worktree",
            side_effect=WorktreeError("worktree creation failed"),
        ) as ensure,
    ):
        reconcile_worktrees_at_startup({"owner/repo": ["group"]})
    ensure.assert_called_once_with("group", repo_context)


def test_startup_rebase_handles_missing_branch_and_divergence_failure(tmp_path: Path) -> None:
    repo_context, runtime = _repo_context(tmp_path)
    repo_context.worktrees_dir.mkdir(parents=True)
    (repo_context.worktrees_dir / "missing-branch").mkdir()
    (repo_context.worktrees_dir / "unknown-divergence").mkdir()
    with (
        patch("pynchy.host.git_ops.worktree._runtime.runtime", runtime),
        patch(
            "pynchy.host.git_ops.worktree.repo_manager.get_repo_context",
            return_value=repo_context,
        ),
        patch(
            "pynchy.host.git_ops.worktree.repo_manager.ensure_repo_cloned",
            return_value=True,
        ),
        patch("pynchy.host.git_ops.worktree.repo_manager.get_repo_token", return_value=None),
        patch("pynchy.host.git_ops.worktree.install_repo_hooks"),
        patch(
            "pynchy.host.git_ops.worktree.run_git", return_value=subprocess.CompletedProcess([], 0)
        ),
        patch("pynchy.host.git_ops.worktree.detect_main_branch", return_value="main"),
        patch(
            "pynchy.host.git_ops.worktree._branch_exists",
            side_effect=[False, True],
        ),
        patch("pynchy.host.git_ops.worktree._worktree_divergence", return_value=None),
    ):
        reconcile_worktrees_at_startup({"owner/repo": []})


def test_startup_rebase_leaves_diverged_worktree_when_rebase_conflicts(
    tmp_path: Path,
) -> None:
    repo_context, runtime = _repo_context(tmp_path)
    repo_context.worktrees_dir.mkdir(parents=True)
    (repo_context.worktrees_dir / "diverged").mkdir()
    with (
        patch("pynchy.host.git_ops.worktree._runtime.runtime", runtime),
        patch(
            "pynchy.host.git_ops.worktree.repo_manager.get_repo_context",
            return_value=repo_context,
        ),
        patch(
            "pynchy.host.git_ops.worktree.repo_manager.ensure_repo_cloned",
            return_value=True,
        ),
        patch("pynchy.host.git_ops.worktree.repo_manager.get_repo_token", return_value=None),
        patch("pynchy.host.git_ops.worktree.install_repo_hooks"),
        patch(
            "pynchy.host.git_ops.worktree.run_git", return_value=subprocess.CompletedProcess([], 0)
        ),
        patch("pynchy.host.git_ops.worktree.detect_main_branch", return_value="main"),
        patch("pynchy.host.git_ops.worktree._branch_exists", return_value=True),
        patch("pynchy.host.git_ops.worktree._worktree_divergence", return_value=(1, 1)),
        patch("pynchy.host.git_ops.worktree._safe_rebase", return_value=False) as rebase,
    ):
        reconcile_worktrees_at_startup({"owner/repo": []})
    rebase.assert_called_once_with("main", cwd=repo_context.worktrees_dir / "diverged")


def test_startup_migrates_old_worktree_when_git_move_succeeds(tmp_path: Path) -> None:
    repo_context, runtime = _repo_context(tmp_path)
    old = runtime.home_dir / ".config" / "pynchy" / "worktrees" / "group"
    old.mkdir(parents=True)
    (old / ".git").write_text("gitdir: /tmp/metadata")
    calls: list[tuple[str, ...]] = []

    def run_git(command: str, *args: str, **_kwargs: object) -> subprocess.CompletedProcess[str]:
        calls.append((command, *args))
        return subprocess.CompletedProcess([], 0)

    _reconcile(repo_context, runtime, git_runner=run_git)
    assert any(call[:2] == ("worktree", "move") for call in calls)


def test_startup_removes_old_worktree_when_git_move_fails(tmp_path: Path) -> None:
    repo_context, runtime = _repo_context(tmp_path)
    old = runtime.home_dir / ".config" / "pynchy" / "worktrees" / "group"
    old.mkdir(parents=True)
    (old / ".git").write_text("gitdir: /tmp/metadata")

    def run_git(command: str, *args: str, **_kwargs: object) -> subprocess.CompletedProcess[str]:
        if command == "worktree" and args[:1] == ("move",):
            return subprocess.CompletedProcess([], 1, "", "move failed")
        if command == "worktree" and args[:1] == ("remove",):
            return subprocess.CompletedProcess([], 1, "", "remove failed")
        return subprocess.CompletedProcess([], 0)

    _reconcile(repo_context, runtime, git_runner=run_git)
    assert not old.exists()
