"""Real-process cleanup coverage for a failed deterministic runtime setup."""

from __future__ import annotations

import json
import os
import shutil
import socket
import subprocess  # noqa: S404 - tests manage only harness-owned local runtimes.
from pathlib import Path
from uuid import uuid4

import pytest

pytestmark = pytest.mark.runtime

_COPIED_CHECKOUT_EXCLUSIONS = {
    ".env",
    ".git",
    ".mypy_cache",
    ".new-feature",
    ".pytest_cache",
    ".ruff_cache",
    ".venv",
    ".worktrees",
    "__pycache__",
    "config.toml",
    "groups",
    "litellm_config.yaml",
    "logs",
}


@pytest.mark.timeout(180)
def test_failed_setup_removes_processes_and_docker_resources(tmp_path: Path) -> None:
    """An error after semantic readiness leaves no runtime-owned resource behind."""
    source_root = Path(__file__).resolve().parents[2]
    failure_root = tmp_path / "failed-runtime"
    shutil.copytree(source_root, failure_root, ignore=_ignore_runtime_artifacts)
    namespace = f"pynchy-runtime-failure-{uuid4().hex[:10]}"
    environment = _runtime_environment()

    try:
        result = subprocess.run(  # noqa: S603 - fixed repository-local failure probe.
            [  # noqa: S607 - uv is the repository's required Python runner.
                "uv",
                "run",
                "python",
                "-m",
                "tests.runtime.partial_start_failure",
                "--root",
                str(failure_root),
                "--namespace",
                namespace,
            ],
            cwd=source_root,
            env=environment,
            capture_output=True,
            check=False,
            text=True,
            timeout=180,
        )
        assert result.returncode == 0

        assert not (failure_root / "data" / "pynchy-runtime" / "runtime.json").exists()
        result_payload = json.loads(
            (failure_root / "data" / "pynchy-runtime" / "partial-start-result.json").read_text(
                encoding="utf-8"
            )
        )
        assert isinstance(result_payload, dict)
        agent_image = result_payload["agent_image"]
        assert isinstance(agent_image, str)
        assert agent_image.startswith(f"pynchy-runtime-agent:{namespace}-")
        for key in ("server_port", "gateway_port", "temporal_port"):
            port = result_payload[key]
            assert isinstance(port, int)
            _assert_port_is_unused(port)

        _assert_docker_resource_is_gone("container", f"{namespace}-pynchy")
        _assert_docker_resource_is_gone("container", f"{namespace}-litellm")
        _assert_docker_resource_is_gone("container", f"{namespace}-litellm-db")
        _assert_docker_resource_is_gone("container", f"{namespace}-deterministic-openai")
        _assert_docker_resource_is_gone("network", f"{namespace}-litellm-net")
        _assert_docker_resource_is_gone("volume", f"{namespace}-litellm-db-data")
        _assert_docker_resource_is_gone("image", agent_image)
    finally:
        subprocess.run(  # noqa: S603 - best-effort cleanup of a test-owned root.
            [  # noqa: S607 - uv is the repository's required Python runner.
                "uv",
                "run",
                "python",
                "scripts/runtime_harness.py",
                "--root",
                str(failure_root),
                "stop",
            ],
            cwd=source_root,
            env=environment,
            capture_output=True,
            check=False,
            text=True,
            timeout=90,
        )


def _ignore_runtime_artifacts(directory: str, names: list[str]) -> set[str]:
    if Path(directory).name == "data":
        return set(names) - {"defaults"}
    return {name for name in names if name in _COPIED_CHECKOUT_EXCLUSIONS}


def _runtime_environment() -> dict[str, str]:
    environment = dict(os.environ)
    for name in (
        "GATEWAY__PORT",
        "NEW_FEATURE_TEMPORAL_PORT",
        "PYNCHY_RUNTIME_NAMESPACE",
        "SERVER__PORT",
    ):
        environment.pop(name, None)
    return environment


def _assert_port_is_unused(port: int) -> None:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as connection:
        assert connection.connect_ex(("127.0.0.1", port)) != 0


def _assert_docker_resource_is_gone(resource_type: str, name: str) -> None:
    result = subprocess.run(  # noqa: S603 - name is generated by the harness namespace.
        [  # noqa: S607 - Docker is a required local runtime executable.
            "docker",
            resource_type,
            "inspect",
            name,
        ],
        capture_output=True,
        check=False,
        text=True,
        timeout=30,
    )
    assert result.returncode != 0
