"""Built-in semantic action declarations, grouped independently from their contract."""

from __future__ import annotations

from pynchy._action_contract import ActionSpec, ActionSurface, ActionTransport
from pynchy._action_spec_helpers import agent_action, build_action, mcp_action
from pynchy._action_specs_core import CORE_ACTION_SPECS

# NOTE: Update docs/architecture/action-coverage.md when changing action
# evidence requirements or the canary contract.
ACTION_SPECS: tuple[ActionSpec, ...] = (
    *CORE_ACTION_SPECS,
    agent_action(
        "desktop.screenshot.capture",
        "desktop-screenshot",
        "Capture a host desktop screenshot for a workspace.",
        "take_screenshot",
        canary="desktop.screenshot.round.trip",
    ),
    agent_action(
        "desktop.screenshot.analyze",
        "desktop-screenshot",
        "Analyze a workspace desktop screenshot with a vision model.",
        "analyze_screenshot",
        canary="desktop.screenshot.round.trip",
    ),
    build_action(
        "desktop.computer.capture",
        "computer-use",
        "Capture an application window and its accessibility state.",
        ActionSurface(ActionTransport.AGENT_TOOL, "computer_use", "capture"),
        canary="desktop.computer.round.trip",
    ),
    build_action(
        "desktop.computer.app.list",
        "computer-use",
        "List desktop applications.",
        ActionSurface(ActionTransport.AGENT_TOOL, "computer_use", "list_apps"),
        canary="desktop.computer.round.trip",
    ),
    build_action(
        "desktop.computer.window.list",
        "computer-use",
        "List desktop windows.",
        ActionSurface(ActionTransport.AGENT_TOOL, "computer_use", "list_windows"),
        canary="desktop.computer.round.trip",
    ),
    build_action(
        "desktop.computer.app.launch",
        "computer-use",
        "Launch a desktop application.",
        ActionSurface(ActionTransport.AGENT_TOOL, "computer_use", "launch_app"),
        canary="desktop.computer.round.trip",
    ),
    build_action(
        "desktop.computer.click",
        "computer-use",
        "Click a desktop element or coordinate.",
        ActionSurface(ActionTransport.AGENT_TOOL, "computer_use", "click"),
        canary="desktop.computer.round.trip",
    ),
    build_action(
        "desktop.computer.double.click",
        "computer-use",
        "Double-click a desktop element or coordinate.",
        ActionSurface(ActionTransport.AGENT_TOOL, "computer_use", "double_click"),
        canary="desktop.computer.round.trip",
    ),
    build_action(
        "desktop.computer.right.click",
        "computer-use",
        "Right-click a desktop element or coordinate.",
        ActionSurface(ActionTransport.AGENT_TOOL, "computer_use", "right_click"),
        canary="desktop.computer.round.trip",
    ),
    build_action(
        "desktop.computer.text.type",
        "computer-use",
        "Type text into a desktop application.",
        ActionSurface(ActionTransport.AGENT_TOOL, "computer_use", "type"),
        canary="desktop.computer.round.trip",
    ),
    build_action(
        "desktop.computer.key.send",
        "computer-use",
        "Send a keyboard shortcut to a desktop application.",
        ActionSurface(ActionTransport.AGENT_TOOL, "computer_use", "key"),
        canary="desktop.computer.round.trip",
    ),
    build_action(
        "desktop.computer.scroll",
        "computer-use",
        "Scroll a desktop application.",
        ActionSurface(ActionTransport.AGENT_TOOL, "computer_use", "scroll"),
        canary="desktop.computer.round.trip",
    ),
    build_action(
        "desktop.computer.wait",
        "computer-use",
        "Wait for a desktop application to settle.",
        ActionSurface(ActionTransport.AGENT_TOOL, "computer_use", "wait"),
        canary="desktop.computer.round.trip",
    ),
    build_action(
        "desktop.computer.permissions.check",
        "computer-use",
        "Check host accessibility permissions for computer use.",
        ActionSurface(ActionTransport.AGENT_TOOL, "computer_use", "check_permissions"),
        canary="desktop.computer.round.trip",
    ),
    agent_action(
        "integration.google.profile.setup",
        "google-setup",
        "Set up Google services for an authorized browser profile.",
        "setup_google_{profile}",
        canary="google.profile.setup",
    ),
    agent_action(
        "integration.slack.session.setup",
        "slack-token-extractor",
        "Create a persistent Slack browser session through interactive login.",
        "setup_slack_session",
        canary="slack.session.setup",
    ),
    agent_action(
        "integration.slack.tokens.refresh",
        "slack-token-extractor",
        "Refresh Slack browser tokens from a persistent authenticated session.",
        "refresh_slack_tokens",
        canary="slack.tokens.refresh",
    ),
    agent_action(
        "social.x.session.setup",
        "x-integration",
        "Create a persistent X browser session through interactive login.",
        "setup_x_session",
        canary="social.x.session.setup",
    ),
    agent_action(
        "social.x.post",
        "x-integration",
        "Publish a post to X.",
        "x_post",
        canary="social.x.round.trip",
    ),
    agent_action(
        "social.x.like",
        "x-integration",
        "Like a post on X.",
        "x_like",
        canary="social.x.round.trip",
    ),
    agent_action(
        "social.x.reply",
        "x-integration",
        "Reply to a post on X.",
        "x_reply",
        canary="social.x.round.trip",
    ),
    agent_action(
        "social.x.repost",
        "x-integration",
        "Repost a post on X.",
        "x_retweet",
        canary="social.x.round.trip",
    ),
    agent_action(
        "social.x.quote",
        "x-integration",
        "Quote a post on X.",
        "x_quote",
        canary="social.x.round.trip",
    ),
    mcp_action(
        "linear.team.list",
        "linear",
        "List teams available through the configured Linear workspace.",
        "linear_list_teams",
        canary="linear.workspace.round.trip",
    ),
    mcp_action(
        "linear.issue.list",
        "linear",
        "List issues from the configured Linear workspace.",
        "linear_list_issues",
        canary="linear.workspace.round.trip",
    ),
    mcp_action(
        "linear.issue.create",
        "linear",
        "Create an issue in a selected Linear team.",
        "linear_create_issue",
        canary="linear.workspace.round.trip",
    ),
    mcp_action(
        "linear.todo.list",
        "linear",
        "List Linear todo issues for a Pynchy workspace.",
        "linear_list_todos",
        canary="linear.workspace.round.trip",
    ),
    mcp_action(
        "linear.todo.create",
        "linear",
        "Create a Linear todo issue for a Pynchy workspace.",
        "linear_create_todo",
        canary="linear.workspace.round.trip",
    ),
    mcp_action(
        "linear.todo.move",
        "linear",
        "Move a Linear todo issue to a Pynchy todo status.",
        "linear_move_todo",
        canary="linear.workspace.round.trip",
    ),
    mcp_action(
        "mail.proton.mailbox.list",
        "proton-mail",
        "List mailboxes available through Proton Bridge.",
        "proton_list_mailboxes",
        canary="proton.mail.read",
    ),
    mcp_action(
        "mail.proton.message.list",
        "proton-mail",
        "List messages from a Proton Mail mailbox.",
        "proton_list_mail",
        canary="proton.mail.read",
    ),
    mcp_action(
        "mail.proton.message.read",
        "proton-mail",
        "Read a Proton Mail message without changing its read state.",
        "proton_read_mail",
        canary="proton.mail.read",
    ),
    mcp_action(
        "notebook.kernel.start",
        "notebook-server",
        "Start an isolated notebook kernel.",
        "start_kernel",
    ),
    mcp_action(
        "notebook.cell.execute",
        "notebook-server",
        "Execute code in an active notebook kernel.",
        "execute_cell",
    ),
    mcp_action(
        "notebook.markdown.add",
        "notebook-server",
        "Add markdown to an active notebook.",
        "add_markdown",
    ),
    mcp_action(
        "notebook.file.save",
        "notebook-server",
        "Save an active notebook under a new name.",
        "save_as",
    ),
    mcp_action("notebook.file.read", "notebook-server", "Read a saved notebook.", "read_notebook"),
    mcp_action("notebook.file.list", "notebook-server", "List saved notebooks.", "list_notebooks"),
    mcp_action(
        "notebook.kernel.list", "notebook-server", "List active notebook kernels.", "list_kernels"
    ),
    mcp_action(
        "notebook.kernel.stop",
        "notebook-server",
        "Shut down an active notebook kernel.",
        "shutdown_kernel",
    ),
)
