"""Generated Codex CLI configuration for Pynchy sandboxes."""

from __future__ import annotations

import json
import os
import re
import sys
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from pathlib import Path

_SAFE_TOML_KEY = re.compile(r"^[A-Za-z0-9_-]+$")
_PYNCHY_LITELLM_PROVIDER = "pynchy_litellm"
# Pynchy's container and mount policy are the isolation boundary. Codex's
# inner bubblewrap layer rejects tracked symlinked instruction dirs such as
# .agents -> .claude inside a writable project mount.
DEFAULT_CODEX_SANDBOX_MODE = "danger-full-access"


def _toml_key(key: str) -> str:
    """Return a TOML bare key when safe, otherwise a quoted key segment."""
    if _SAFE_TOML_KEY.fullmatch(key):
        return key
    return json.dumps(key)


def _toml_value(value: Any) -> str:
    """Serialize the small TOML value subset this generated config needs."""
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int | float):
        return str(value)
    if isinstance(value, str):
        return json.dumps(value)
    if isinstance(value, list | tuple):
        return "[" + ", ".join(_toml_value(item) for item in value) + "]"
    raise TypeError(f"Unsupported TOML value: {value!r}")


def _append_mapping_table(lines: list[str], name: str, values: Any) -> None:
    if not isinstance(values, dict) or not values:
        return
    lines.extend(["", f"[{name}]"])
    for key, value in values.items():
        lines.append(f"{_toml_key(str(key))} = {_toml_value(str(value))}")


def _mcp_server_lines(name: str, spec: dict[str, Any]) -> list[str]:
    """Render one Pynchy MCP server spec as Codex ``config.toml``."""
    server = f"mcp_servers.{_toml_key(name)}"
    direct_keys = (
        "command",
        "args",
        "cwd",
        "url",
        "startup_timeout_sec",
        "tool_timeout_sec",
        "enabled",
        "required",
        "default_tools_approval_mode",
        "enabled_tools",
        "disabled_tools",
        "bearer_token_env_var",
    )
    lines = ["", f"[{server}]"]
    for key in direct_keys:
        value = spec.get(key)
        if value is not None:
            lines.append(f"{_toml_key(key)} = {_toml_value(value)}")
    if spec.get("auth_value_env") and spec.get("bearer_token_env_var") is None:
        lines.append(f"bearer_token_env_var = {_toml_value(spec['auth_value_env'])}")

    _append_mapping_table(lines, f"{server}.env", spec.get("env"))
    _append_mapping_table(
        lines, f"{server}.http_headers", spec.get("http_headers") or spec.get("headers")
    )
    _append_mapping_table(lines, f"{server}.env_http_headers", spec.get("env_http_headers"))

    return lines


def _append_v1(base_url: str) -> str:
    """Normalize a gateway root URL to the OpenAI ``/v1`` API base."""
    normalized = base_url.rstrip("/")
    return normalized if normalized.endswith("/v1") else f"{normalized}/v1"


def gateway_base_url_from_env() -> str:
    missing = [
        name
        for name in ("OPENAI_BASE_URL", "OPENAI_API_KEY")
        if not os.environ.get(name, "").strip()
    ]
    if missing:
        joined = ", ".join(missing)
        raise RuntimeError(f"Codex core requires {joined} from the Pynchy LLM gateway")
    return _append_v1(os.environ["OPENAI_BASE_URL"])


def write_codex_config(
    codex_home: Path,
    mcp_servers: dict[str, dict[str, Any]],
    *,
    gateway_base_url: str,
) -> None:
    """Write the Pynchy-managed Codex CLI config for this per-group home."""
    codex_home.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Generated by Pynchy for this sandbox. LLM auth is routed through LiteLLM.",
        'approval_policy = "never"',
        f"sandbox_mode = {_toml_value(DEFAULT_CODEX_SANDBOX_MODE)}",
        f"model_provider = {_toml_value(_PYNCHY_LITELLM_PROVIDER)}",
        "",
        f"[model_providers.{_PYNCHY_LITELLM_PROVIDER}]",
        'name = "Pynchy LiteLLM Gateway"',
        f"base_url = {_toml_value(gateway_base_url)}",
        'wire_api = "responses"',
        'env_key = "OPENAI_API_KEY"',
        "",
        "[features]",
        "hooks = true",
        "",
        "[sandbox_workspace_write]",
        "network_access = true",
        "",
        "[[hooks.PreToolUse]]",
        'matcher = "*"',
        "",
        "[[hooks.PreToolUse.hooks]]",
        'type = "command"',
        f"command = {_toml_value(f'{sys.executable} -m agent_runner.security.hook_entry')}",
        "timeout = 30",
        'statusMessage = "Checking Pynchy security policy"',
    ]

    for name, spec in sorted(mcp_servers.items()):
        lines.extend(_mcp_server_lines(name, spec))

    (codex_home / "config.toml").write_text("\n".join(lines) + "\n")
